module.exports = {
  source: ['figma-tokens.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`Do not edit directly, this file was auto-generated`];
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/',
      files: [
        {
          destination: 'open-props.css',
          format: 'css/variables',
          options: {
            selector: ':where(html)',
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
};
